
from PyQt5 import QtCore

# Mock resources to prevent ImportErrors
# In a real build, this would be generated by pyrcc5
qt_resource_data = b""
qt_resource_name = b""
qt_resource_struct = b""

def qInitResources():
    pass

def qCleanupResources():
    pass
